raemos/config/routes.rb
Raemos::Application.routes.draw do
  
  resource :admin, except: [:destroy, :show, :edit] do
    get :index
    
    collection do
      get :users, action: "show_users", as: "users"
      get :admins, action: "show_admins", as: "list"
    end
    member do
      delete "/destroy/:id" => "admins#destroy", as: "destroy"
      post "/reset_admin_password/:id" => "admins#reset_admin_password", as: "reset_password"  
    end 
    
    get "/show" => "admins#show", as: "show"        
  end

  get "home/index"

  resource :user, except: [:new, :create, :destroy, :show, :edit] do
    get :index
    post "create" => "users#create", as: "create"
    member do
      delete "destroy/:id" => "users#destroy", as: "destroy"
    end
  end

  post "session/authorize" => "session#authorize", as: "authorize"
  get "session/logout" => "session#logout", as: "logout"

  root to: "home#index"

end

raemos/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user
    	if user.is_admin?
    		if user.is_super_admin?
    			can :manage, :all	
    		else
    			can :manage, Admin
    			cannot [:create, :show_admins, :reset_admin_password], Admin
    			can :destroy, Admin do |destroy_admin|
    				destroy_admin == user
    			end
                can :destroy, User
    		end

    	else
    		can :manage, User
    		can :destroy, User do |destroy_user|
    			destroy_user == user
    		end
            can :update, User do |update_user|
                update_user == user
            end
    	end
    end

  end
end

raemos/app/models/admin/admin.rb
class Admin < ActiveRecord::Base
  include UserSkeleton

  def is_super_admin?
    self.class.name == "SuperAdmin"
  end

  def is_admin?
    true
  end
end

raemos/app/models/admin/simple_admin.rb
class SimpleAdmin < Admin
  def self.model_name
    Admin.model_name
  end
end

raemos/app/models/admin/super_admin.rb
class SuperAdmin < Admin
  def self.model_name
    Admin.model_name
  end
end

raemos/app/models/user.rb
class User < ActiveRecord::Base
  include UserSkeleton
end

raemos/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def show
    @admin = admin_user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = params[:isSuper] ? SuperAdmin.new(params[:admin]) : SimpleAdmin.new(params[:admin]); 
    @admin.encrypt_password(@admin.password)
    @admin.save

    redirect_to action: "index"
  end

  def update
    @user = Admin.authenticate(current_user.email, params[:admin][:password])
    @errors = [];
    if @user 
      @user.new_password_confirmation = params[:new_password_confirmation]
      @user.new_password = params[:new_password]  

      if !@user.update_attributes(params[:admin])
        @errors = @user.errors
      end
    else
      @errors = ["Password is incorrect"]
    end
  end

  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy
    if @admin && @admin.id == current_user.id
      remove_user_from_session
      redirect_to root_path
    end

    render json: {}
  end

  def show_users
    @sort_column = params[:column] || "first_name"
    @direction = params[:direction] == "desc"? "asc" : "desc";
    @users = User.order("#{@sort_column} #{@direction}")
  end

  def show_admins
    @sort_column = params[:column] || "first_name"
    @direction = params[:direction] == "desc"? "asc" : "desc";
    @admins = Admin.order("#{@sort_column} #{@direction}")
  end

  def reset_admin_password
    @admin = Admin.find(params[:id])
    if @admin
      @admin.update_attribute(:password, ""); #empty pass hash
    end

    render json: {}
  end

  private 

  def add_user_to_session(user_id)
    session[:admin_user_id] = user_id;
  end 

  def remove_user_from_session()
    session.delete(:admin_user_id)
  end
end

raemos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  layout :determine_layout


  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end


  private

  def determine_layout
    current_user ? "user" : "application"
  end

  def current_user
    @current_user ||= (session[:is_admin]? Admin.find(session[:user_id]) : User.find(session[:user_id])) if session[:user_id]
  end

  private 

  def add_user_to_session(user_id, is_admin)
    session[:user_id] = user_id
    session[:is_admin] = is_admin
  end

  def remove_user_from_session
    session.delete(:user_id)
    session.delete(:is_admin)
  end
end

raemos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
	  	if @current_user.is_admin?
	  		redirect_to controller: "admins"
	  	else
	  		redirect_to controller: "users"
	  	end
	end
  end
end

raemos/app/controllers/session_controller.rb
class SessionController < ApplicationController

	def authorize
		@user = params[:is_admin] == "true" ? Admin.authenticate(params[:email], params[:password]) : User.authenticate(params[:email], params[:password])
		
		result_json = {status: "done"}
		if @user
			add_user_to_session(@user.id, @user.is_admin?)
		else 
			result_json = {
				status: "error",
				message: ["Login or pass is incorrect"]
			}
			
		end
		
		render json: result_json
	end

	def logout
		remove_user_from_session
		redirect_to root_path		
	end
end

raemos/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def create
    @user = User.new(params[:user])
    @user.encrypt_password(@user.password)          


    result_json = {status: "done"}

    if @user.save
      session[:user_id] = @user.id
    else
      result_json = {status: "error", message: @user.errors}
    end

    render json: result_json
  end

  def update
    @user = User.authenticate(current_user.email, params[:user][:password])

    @errors = [];
    if @user 
      @user.new_password_confirmation = params[:new_password_confirmation]
      @user.new_password = params[:new_password]  

      if !@user.update_attributes(params[:user])
        @errors = @user.errors
      end
    else
      @errors = ["Password is incorrect"]
    end
  end

  def destroy    
    @user = User.find(params[:id])
    @user.destroy
   
    render json: {}
  end
end

raemos/app/helpers/admins_helper.rb
module AdminsHelper
end

raemos/app/helpers/application_helper.rb
module ApplicationHelper
end

raemos/app/helpers/home_helper.rb
module HomeHelper
end

raemos/app/helpers/users_helper.rb
module UsersHelper
end

raemos/app/views/admins/_admins.html.erb
<table id="table_sortable_<%=@direction%>">
	<tr>
      <th>
        <%= link_to "First name", list_admin_path(:column => "first_name", direction: @direction ), onclick: "$.getScript(this.href); return false" %>
        <% if @sort_column == "first_name"%>
          <span class="direction_asc"><</span>
          <span class="direction_desc">></span>
        <%end%>
      </th>
      <th>
        <%= link_to "Last name", list_admin_path(:column => "last_name", direction: @direction), onclick: "$.getScript(this.href); return false" %>
        <% if @sort_column == "last_name"%>
          <span class="direction_asc"><</span>
          <span class="direction_desc">></span>
        <%end%>
      </th>
      <th>
        <%= link_to "Email", list_admin_path(:column => "email", direction: @direction), onclick: "$.getScript(this.href); return false" %>
        <% if @sort_column == "email"%>
          <span class="direction_asc"><</span>
          <span class="direction_desc">></span>
        <%end%>
      </th>
      <th>Action</th>
    </tr>
	<%@admins.each do |admin| %>
		<% if admin.id != session[:user_id] %>
			<tr>
				<td>
					<%=admin.first_name%>
				</td>
				<td>
					<%=admin.last_name%>
				</td>
				<td>
					<%=admin.email%>
				</td>
				<td>
					<%= link_to 'Delete', destroy_admin_path(admin.id), class: "delete_admin", method: "delete" %>,
					<%=link_to "Reset password", reset_password_admin_path(admin.id), method: "post", remote: true%>
				</td>
			</tr>
		<%end%>
	<%end%>
</table>

raemos/app/views/admins/_form.html.erb
<div class="inputDesign">
  <%= form_for @admin, form_options  do |f| %>
    <% if @admin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

        <ul>
        <% @admin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :first_name, {placeholder: "First name"} %>
    </div>
    <div class="field">
      <%= f.text_field :last_name, {placeholder: "Last name"} %>
    </div>
    <div class="field">
      <%= f.text_field :email, {placeholder: "Email"} %>
    </div>
    <div class="field">
      <%= f.password_field :password, {placeholder: "Password"} %> 
    </div>

    <% if isCreate %>
      <div class="field">
        <%= check_box_tag "isSuper"%> - Is super admin
      </div>
    <%end%> 
    
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

raemos/app/views/admins/_users.html.erb
<table id="table_sortable_<%=@direction%>">
    <tr>
      <th>
        <%= link_to "First name", users_admin_path(:column => "first_name", direction: @direction ), onclick: "$.getScript(this.href); return false" %>
        <% if @sort_column == "first_name"%>
          <span class="direction_asc"><</span>
          <span class="direction_desc">></span>
        <%end%>
      </th>
      <th>
        <%= link_to "Last name", users_admin_path(:column => "last_name", direction: @direction), onclick: "$.getScript(this.href); return false" %>
        <% if @sort_column == "last_name"%>
          <span class="direction_asc"><</span>
          <span class="direction_desc">></span>
        <%end%>
      </th>
      <th>
        <%= link_to "Email", users_admin_path(:column => "email", direction: @direction), onclick: "$.getScript(this.href); return false" %>
        <% if @sort_column == "email"%>
          <span class="direction_asc"><</span>
          <span class="direction_desc">></span>
        <%end%>
      </th>
      <th>Action</th>
    </tr>


    <% @users.each do |user| %>
      <tr id="user_<%=user.id%>">

        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>

        <td>
          <%= link_to 'Destroy', destroy_user_path(user.id), class: "delete_user", method: :delete, data: { confirm: 'Are you sure?'} %>
        </td>

      </tr>
    <% end %>
  </table>

raemos/app/views/admins/edit.html.erb
<h1>Editing admin</h1>
<%= render partial: 'form', locals: {isCreate: false, form_options: {url: admins_path, method: "PUT"}} %>

<%= link_to 'Show', show_admins_path %> |
<%= link_to 'Back', admin_path %>

raemos/app/views/admins/login.html.erb
<div class="windowStyle" id="authorizeForm">
    <span>Log in</span>
    <br/><br/>

    <%= form_tag authorize_admins_path do%>
    
    <div class="inputContainer">
    	<%= text_field_tag :email, params[:email], {placeholder: "Email"} %>
    </div>
	<div class="inputContainer">
    	<%= password_field_tag :password, nil, {placeholder: "Password"} %>
    </div>		
    
    <div class="inputContainer">
    	<%= submit_tag "Log in" %>
    </div>

    <div class="errorMessage"></div>
    

    <%end%>

    <%= link_to "Back", admin_path %>    
</div>

raemos/app/views/admins/new.html.erb
<div align="center">
	<%= render partial: 'form', locals: {isCreate: true, form_options: {url: admin_path, method: "POST"}} %>
</div>

<%= link_to 'Back', admin_path %>

raemos/app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @admin.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @admin.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @admin.email %>
</p>


<%= link_to 'Edit', edit_admin_path %> |
<%= link_to 'Back', admins_path %>

raemos/app/views/admins/show_admins.html.erb
<%=link_to "Back", admin_path %>
<br>
<br>

<div id="admins">
	<%= render "admins"%>
</div>

raemos/app/views/admins/show_admins.js.erb
$("#admins").html("<%= escape_javascript(render "admins")%>");

raemos/app/views/admins/show_users.html.erb
<%= link_to "Back", admin_path %>

<br>
<br>
<%= hidden_field_tag :direction, params[:direction] %>
<div id="users">
  <%= render "users"%>
</div>

raemos/app/views/admins/show_users.js.erb
$("#users").html("<%= escape_javascript(render "users")%>");

raemos/app/views/admins/update.js.erb
$('#error_explanation').html("")
<% if !@errors.empty? %>
	<%@errors.each do |error|%>
		var divError = $('<div>').text("<%=error%>");
		$('#error_explanation').append(divError)
	<%end%>
<%else%>
	$("#profile_first_name").text("<%=@user.first_name%>")
	$("#profile_last_name").text("<%=@user.last_name%>")
	$("#profile_email").text("<%=@user.email%>")
	hideDioPopups()
<%end%>

raemos/app/views/home/index.html.erb
<div align="center"><h1>News</h1></div>

raemos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raemos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>

      <div id="mainContainer">
          <div id="headerContainer" class="windowStyle">
              <div id="logo">
                  <%= link_to 'Raemos', root_path %>
              </div>            
              <div id="loginButton">
                  <%= link_to 'Log in', "#", id: "loginLink", onclick: "showAuthenicatePopup()" %>
              </div>
          </div>

          <div id="bodyContainer" class="windowStyle">
              <div id="changedContent">
                  <%= yield %>
              </div>
          </div>
      </div>


     

      <div class="dioBackgroundOverlay">
        
        <div class="windowStyle dioPopup" id="signinPopup">
          <div class="closePopupBtn">x</div>
          <%= render :partial => "popups/login_form" %>
        </div>


        <div class="windowStyle dioPopup" id="registrationPopup">
          <div class="closePopupBtn">x</div>
          <%= render :partial => "popups/registration_form" %>
        </div>

      </div>
        




  </body>
</html>

raemos/app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raemos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="authorized_user_body">

    <div id="userProfileContent" class="windowStyle">
      <div id="profileContailner">
        <div id="imgContainer">
          <%=image_tag("default_user.jpg")%>
        </div>
        <div id="profileInfo">
          <div id="editUserLinkContainer"> 
            <%=link_to "Edit", "#", onclick: "showEditUserPopup()"%>
          </div>
          <div>
            Name: <span id="profile_first_name"><%=current_user.first_name%></span>
          </div>
          <div>
            Surname: <span id="profile_last_name"><%=current_user.last_name%></span>
          </div>
          <div>
            Email: <span id="profile_email"><%=current_user.email%></span>
          </div>

        </div>
      </div>
    </div>

    <div id="userActionsContainer" class="windowStyle">
      <div>
        User actions:
      </div>
      <hr>
      <%= link_to 'log out ', logout_path%><br>
      <%if can? :read, Admin %>
        <%= link_to 'Show all users', users_admin_path %><br>


        <%if can? :show_admins, Admin%>
          <%= link_to 'Show all admins', list_admin_path %><br>
          <%= link_to 'Register new admin', new_admin_path %>
        <%end%>
        
      <%else%>
        
      <%end%>
    </div>

    <div id="bodyContainer" class="windowStyle">
        <div id="changedContent">
            <%= yield %>
        </div>
    </div>


   

    <div class="dioBackgroundOverlay">
      
      <div class="windowStyle dioPopup" id="signinPopup">
        <div class="closePopupBtn">x</div>
        <%= render :partial => "popups/login_form" %>
      </div>


      <div class="windowStyle dioPopup" id="registrationPopup">
        <div class="closePopupBtn">x</div>
        <%= render :partial => "popups/registration_form" %>
      </div>


      <div class="windowStyle dioPopup" id="editUserPopup">
        <div class="closePopupBtn">x</div>
        <%= render :partial => "popups/edit_form" %>
      </div>
    </div>
    
</body>
</html>

raemos/app/views/popups/_edit_form.html.erb
<%= form_for current_user, remote: true do |f| %>
  

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :new_password %><br />
    <%= password_field_tag :new_password %>
  </div>

  <div class="field">
    <%= label_tag :new_password_confirmation %><br />
    <%= password_field_tag :new_password_confirmation%>
  </div>


  <div id="error_explanation">
    
  </div>
  


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

raemos/app/views/popups/_login_form.html.erb
<div id="authorizeForm">
    <span>Log in</span>
    <br/><br/>
    
    <div class="inputContainer">
    	<%= text_field_tag :authorize_email_field, params[:email], {placeholder: "Email"} %>
    </div>
	<div class="inputContainer">
    	<%= password_field_tag :authorize_password_field, nil, {placeholder: "Password"} %>
    </div>		
    
    <div class="inputContainer">
        <label>
            <%= check_box_tag "is_admin"%> 
            <span>
                - Login by admin
            </span>
        </label>
    </div>

    <div class="inputContainer">
    	<%= button_tag "Log in", {id: "authorize_btn", authorize_path: authorize_path,:onclick=>"authorizeUser()"} %>
    </div>

    <div class="errorMessage"></div>
    
    <%= link_to "Register new user", "#", {:onclick => "showRegistrationPopup()"} %>

    
</div>

raemos/app/views/popups/_registration_form.html.erb
<div class="windowStyle" id="registrationForm">
    <span>Registration new user</span>

    <div class="inputContainer">
    	<%= text_field_tag :reg_first_name, nil, {placeholder: "First name"}%>
	</div>
    <div class="inputContainer">
    	<%= text_field_tag :reg_last_name, nil, {placeholder: "Last name"}%>
    </div>
    <div class="inputContainer">
    	<%= text_field_tag :reg_email, nil, {placeholder: "Email"}%>
    </div>	
    <div class="inputContainer">
    	<%= password_field_tag :reg_password, nil, {placeholder: "Password"}%>
    </div>	
    <div class="inputContainer">
    	<%= password_field_tag :reg_confirm_password, nil, {placeholder: "Confirm password"}%>
   	</div>		
	<div class="inputContainer">
    	<%= button_tag "Sign up", {href: create_user_path, onclick: "registerNewUser(this)"} %>
    </div>
    <div class="errorMessage"></div>

	<%= link_to "I already have account", "#", {onclick: "showAuthenicatePopup()"} %>
</div>

raemos/app/views/users/_form.html.erb
<%= form_for current_user, remote: true do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

raemos/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

raemos/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

raemos/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= current_user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= current_user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= current_user.email %>
</p>


<%= link_to 'Back', user_path %>

raemos/app/views/users/signin.html.erb
<div class="windowStyle" id="signInForm">
    <span>Log in</span>
    <br/><br/>

    <%= text_field_tag :email, params[:email], {placeholder: "Email"} %>
    <br/>
    <%= password_field_tag :password, nil, {placeholder: "Password"} %>
    <br/>
    <input type="button" id="logged_in" onclick="authorizeUser()" value="Sign in"/>
    <br/>





    <%= link_to 'Register new user' %>
</div>

raemos/app/views/users/update.js.erb
$('#error_explanation').html("")
<% if !@errors.empty? %>
	<%@errors.each do |error|%>
		var divError = $('<div>').text("<%=error%>");
		$('#error_explanation').append(divError)
	<%end%>
<%else%>
	$("#profile_first_name").text("<%=@user.first_name%>")
	$("#profile_last_name").text("<%=@user.last_name%>")
	$("#profile_email").text("<%=@user.email%>")
	hideDioPopups()
<%end%>