nigthdev/config/routes.rb
Rails.application.routes.draw do

  get "users/edit"
  post "users/update"

  get 'home/index'

  root 'home#index'

  get "account/signup" => "account#new", :as => "sign_up"
  get "account/signin" => "account#index", :as => "sign_in"
  post "account/logging_user" => "account#logging_user", :as => "logging_user"
  get "account/log_out" => "account#destroy", :as => "log_out"

  post "account/create"

end

nigthdev/app/models/user.rb
class User < ActiveRecord::Base
    validates :email, uniqueness: {message: "Email already used"}
    #before_save :encrypt_password

    def self.authenticate(email, password)
        user = find_by_email(email)
        user = (user && user.password == Digest::MD5.hexdigest(password)) ? user : nil
    end

    def self.encrypt_password(pass)
        Digest::MD5.hexdigest(pass)
    end
end

nigthdev/app/controllers/account_controller.rb
class AccountController < ApplicationController
  protect_from_forgery

  def index

  end

  def new

  end

  def create
    user = User.new({
        :username => params[:user][:username],
        :first_name => params[:user][:first_name],
        :last_name => params[:user][:last_name],
        :email => params[:user][:email],
        :password => User.encrypt_password(params[:user][:password])
    })

    if user.save
        session[:user_id] = user.id
        redirect_to controller:"home", action: "index"
    else
        render :new
    end
  end

  def logging_user
    user = User.authenticate(params[:email], params[:password])
    if user
        session[:user_id] = user.id
        redirect_to controller:"home", action:"index"
    else
        render :index
    end

  end

  def destroy
    session.delete(:user_id)
    render :index
  end

end

nigthdev/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery #with: :exception
    helper_method :current_user

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def check_authorize
        redirect_to sign_in_path unless current_user
    end

end

nigthdev/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

nigthdev/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_authorize

  def edit
  end

  def update
    json_result = {status: "done"}


    user = User.authenticate(current_user.email, params[:password]);


    if user
        print "=============================>#{params[:new_password].empty?}"
       user.password = User.encrypt_password(params[:new_password]) unless params[:new_password].empty?
       print "=============================>#{user.password}"
       unless user.update(
                :username => params[:username],
                :first_name => params[:first_name],
                :last_name => params[:last_name],
                :email => params[:email]
            )

            json_result = {status: "error", message: user.errors}
       end
    else
        json_result = {status: "error", message: ["Password is incorrect"]}
    end



    render json: json_result
  end
end

nigthdev/app/helpers/account_helper.rb
module AccountHelper
end

nigthdev/app/helpers/application_helper.rb
module ApplicationHelper
end

nigthdev/app/helpers/home_helper.rb
module HomeHelper
end

nigthdev/app/helpers/session_helper.rb
module SessionHelper
end

nigthdev/app/helpers/users_helper.rb
module UsersHelper
end

nigthdev/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

nigthdev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nigthdev</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link data-turbolinks-track="true" href="/assets/account.css" media="all" rel="stylesheet" />
</head>
<body>
    <div id="mainContainer">
        <div id="headerContainer" class="windowStyle">
            <div id="logo">
                <%= link_to 'NigthDev', root_path %>
            </div>
            <div id="loginButton">
                <% if current_user%>
                    <div id="userName">
                        Hello: <%= link_to "#{current_user.username}", users_edit_path %>
                    </div>
                    <%= link_to 'Log out', log_out_path %>
                <% else %>
                    <%= link_to 'Log in', sign_in_path %>

                <% end %>
            </div>
        </div>

        <div id="bodyContainer" class="windowStyle">
            <div id="changedContent">
                <%= yield %>
            </div>
        </div>
    </div>

</body>
</html>

nigthdev/app/views/users/edit.html.erb
<div class="windowStyle" id="signInForm">
    <%= text_field_tag :username, current_user.username, {placeholder:"Username"} %>
    <%= text_field_tag :first_name,  current_user.first_name, {placeholder:"First name"} %>
    <%= text_field_tag :last_name, current_user.last_name, {placeholder:"Last name"} %>
    <%= text_field_tag :email, current_user.email, {placeholder:"email"} %>
    <%= password_field_tag :password, nil, { placeholder:"Password"} %>
    <%= password_field_tag :new_password, nil, { placeholder:"New password"} %>
    <%= password_field_tag :confirm_password, nil, { placeholder:"Confirm new password"} %>
    <div id="errorMessage"></div><br>
    <input type="button" value="Save" onclick="saveUserData()"/>
</div>